name: Docker Image CI

on:
  push:
    branches:
      - master

jobs:
  build-all:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Build all Redis images
      run: invoke build --version all --cpu 2
